name: Publish Logseq Graph

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Logseq graph
        uses: logseq/publish-spa@v0.3.0

      - name: Add .nojekyll file
        run: touch $GITHUB_WORKSPACE/www/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
          branch: gh-pages