name: Publish Logseq graph

on: [push]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Publish Logseq graph
    steps:
      - uses: actions/checkout@v4
      
      - uses: logseq/publish-spa@v0.3.0
        with:
          output-directory: 'www' # 明确指定输出到 www 目录

      - name: Add a nojekyll file
        run: touch $GITHUB_WORKSPACE/www/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www # 对应上面打包输出的目录
          branch: gh-pages